[project]
name = "led-sockets"
version = "0.0.0"
requires-python = ">=3.11"

[project.scripts]
ledsockets-client = "ledsockets.client.ClientManager:main"
ledsockets-server = "ledsockets.server.ServerManager:main"
ledsockets = "ledsockets.unified:main"